DROP TABLE comment;
DROP TABLE media;
DROP TABLE user;

CREATE TABLE User (
	id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	username VARCHAR(30) NOT NULL,
	password VARCHAR(64) NOT NULL,
	email VARCHAR(50) NOT NULL,
	img_profile VARCHAR(50) NOT NULL,
	description TEXT
);

CREATE TABLE Media (
	id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	type CHAR(1) NOT NULL,
	title VARCHAR(40)	NOT NULL,
	author VARCHAR(40) NOT NULL,
	genre VARCHAR(50) NOT NULL,
	year VARCHAR(9) NOT NULL,
	in_anime CHAR(1),
	studio VARCHAR(30),
	description text,
	image VARCHAR(50) NOT NULL
);

CREATE TABLE Comment(	
	id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	post_text TEXT NOT NULL,
	ranking CHAR(1) NOT NULL,
	ref_id_user INTEGER UNSIGNED NOT NULL,
	ref_id_media INTEGER UNSIGNED NOT NULL,
	CONSTRAINT fk_user_id FOREIGN KEY (ref_id_user) REFERENCES User(id) ON DELETE CASCADE,
	CONSTRAINT fk_media_id FOREIGN KEY (ref_id_media) REFERENCES Media(id) ON DELETE CASCADE
);